#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "$(git rev-parse --show-toplevel)/src/frontend"
unset GIT_DIR
unset GIT_WORK_TREE

echo "🔍 Running lint-staged from frontend..."
npx lint-staged
