name: Backend Resume Analyzer CI

on:
  push:
    branches: [main, develop]
    paths:
      - "src/backend/XpertSphere.ResumeAnalyzer/**"
      - "docker/backend/resume-analyzer/**"
      - ".github/workflows/backend-resume-analyzer.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "src/backend/XpertSphere.ResumeAnalyzer/**"
      - "docker/backend/resume-analyzer/**"
      - ".github/workflows/backend-resume-analyzer.yml"
  workflow_dispatch:

env:
  REGISTRY: acrxpertspheredev.azurecr.io
  IMAGE_NAME: resume-analyzer-app

jobs:
  # Tests and validation of Pull Requests
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        working-directory: src/backend/XpertSphere.ResumeAnalyzer
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        working-directory: src/backend/XpertSphere.ResumeAnalyzer
        env:
          PYTHONPATH: .
          AZURE_OPENAI_API_KEY: test-key
          AZURE_OPENAI_ENDPOINT: https://test-endpoint
          ENVIRONMENT: test
        run: |
          pytest

  # Build and push for main/develop
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/backend/resume-analyzer/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64

      - name: Test container health
        run: |
          echo "🩺 Testing container health..."
          # Test if the image can start properly
          docker run --rm -d --name test-resume-analyzer -p 8001:8000 \
            -e AZURE_OPENAI_API_KEY=test-key \
            -e ENVIRONMENT=test \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

          # Wait for container to start
          sleep 15

          # Test health endpoint
          if curl -f http://localhost:8001/api/health; then
            echo "Health check passed"
          else
            echo "Health check failed"
            docker logs test-resume-analyzer
            exit 1
          fi

          # Cleanup
          docker stop test-resume-analyzer
