name: Deploy to Azure Container Apps

on:
  workflow_run:
    workflows: ["Candidate App CI/CD", "Recruiter App CI/CD"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging
      force_recreate:
        description: "Force recreate containers (delete and recreate)"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    strategy:
      matrix:
        app:
          - name: "candidate-app"
            container_name: "xpertsphere-candidate-app"
            port: 3000
          - name: "recruiter-app"
            container_name: "xpertsphere-recruiter-app"
            port: 3001

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ${{ matrix.app.name }} to ACA
        run: |
          echo "=== Deploying ${{ matrix.app.name }} ==="

          # Check if container app exists
          if az containerapp show --name ${{ matrix.app.container_name }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} > /dev/null 2>&1; then
            echo "Container app exists, updating..."
            az containerapp update \
              --name ${{ matrix.app.container_name }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --image acrxpertspheredev.azurecr.io/${{ matrix.app.name }}:${{ github.sha }} \
              --set-env-vars VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          else
            echo "Container app doesn't exist, creating..."
            az containerapp create \
              --name ${{ matrix.app.container_name }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --environment ${{ secrets.ACA_ENVIRONMENT_NAME }} \
              --image ${{ matrix.app.image }}:${{ github.sha }} \
              --registry-server acrxpertspheredev.azurecr.io \
              --registry-username ${{ secrets.ACR_USERNAME }} \
              --registry-password ${{ secrets.ACR_PASSWORD }} \
              --target-port ${{ matrix.app.port }} \
              --ingress external \
              --env-vars VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
              --cpu 0.25 \
              --memory 0.5Gi \
              --min-replicas 0 \
              --max-replicas 2
          fi

      - name: Get ${{ matrix.app.name }} URL
        run: |
          echo "🎉 ${{ matrix.app.name }} deployed successfully!"
          echo "🔗 URL: https://$(az containerapp show --name ${{ matrix.app.container_name }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query 'properties.latestRevisionFqdn' -o tsv)"
